data:
  train_lr_dir: "level_2/data/training/lr"
  train_hr_dir: "level_2/data/training/hr/DIV2K_train_HR"
  val_lr_dir: "level_2/data/val/lr"
  val_hr_dir: "level_2/data/val/hr"
  scale_factor: 4  
  num_workers: 8   
  blur_ksize: 3
  noise_var: 10
  
training:
  batch_size: 16
  patch_size: 128
  epochs: 1000
  learning_rate: 1e-4
  loss_weights:
    pixel: 1.0
    perceptual: 0.006
    adversarial: 0.001
  sample_interval: 5   
  checkpoint_interval: 10 
  max_checkpoints: 3  