data:
  train_lr_dir: "data/DIV2K_train_LR"
  train_hr_dir: "data/DIV2K_train_HR"
  val_lr_dir: "data/DIV2K_valid_LR"
  val_hr_dir: "data/DIV2K_valid_HR"
  
training:
  batch_size: 16
  patch_size: 128
  epochs: 1000
  learning_rate: 1e-4
  loss_weights:
    pixel: 1.0
    perceptual: 0.006
    adversarial: 0.001
  sample_interval: 5   
  checkpoint_interval: 10 
  max_checkpoints: 3  